package com.mycompany.basededatos ;



import java.sql.Connection;

import java.sql.PreparedStatement;

import java.sql.SQLException;

import javax.swing.JOptionPane;



/**

*

* @author Limon

*/

public class BaseDeDatos extends javax.swing.JInternalFrame {



/**

* Creates new form MyRegister

*/

public BaseDeDatos() {

initComponents();

this.setLocation(20,20);

}

void insertarDatos(){

conexionMySQL cmysql=new conexionMySQL();

Connection conec=cmysql.Conectar();

String nom,dir,email,comprobacion="";


nom=this.txtNombre.getText();

dir=this.txtDir.getText();

email=this.txtEmail.getText();


String senSQL="INSERT INTO agenda(Nombre,Direccion,Email)VALUES(?,?,?)";

comprobacion="Se an guardado sus datos bien";


try{

PreparedStatement ps=conec.prepareStatement(senSQL);

ps.setString(1, nom);

ps.setString(2, dir);

ps.setString(3, email);


int n=ps.executeUpdate();

if(n>0){

JOptionPane.showOptionDialog(this,comprobacion,"MySQL IFORMATION",JOptionPane.INFORMATION_MESSAGE,

JOptionPane.INFORMATION_MESSAGE,null,new Object[]{"ok"},"ok");

}

}catch(SQLException ex){

JOptionPane.showMessageDialog(null, ex);

}

}


/**

* This method is called from within the constructor to initialize the form.

* WARNING: Do NOT modify this code. The content of this method is always

* regenerated by the Form Editor.

*/

@SuppressWarnings("unchecked")

// <editor-fold defaultstate="collapsed" desc="Generated Code">

private void initComponents() {



panNuevo = new javax.swing.JPanel();

jLabel1 = new javax.swing.JLabel();

jLabel2 = new javax.swing.JLabel();

jLabel3 = new javax.swing.JLabel();

txtNombre = new javax.swing.JTextField();

txtDir = new javax.swing.JTextField();

txtEmail = new javax.swing.JTextField();

btnRegistrar = new javax.swing.JButton();



setIconifiable(true);

setMaximizable(true);

setResizable(true);

setTitle("Ventana Registro de usuarios");



panNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Usuario"));



jLabel1.setText("Nombre:");



jLabel2.setText("Dirección:");



jLabel3.setText("Email");



txtEmail.addActionListener(this::txtEmailActionPerformed);



btnRegistrar.setText("Registrar");

btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);



javax.swing.GroupLayout panNuevoLayout = new javax.swing.GroupLayout(panNuevo);

panNuevo.setLayout(panNuevoLayout);

panNuevoLayout.setHorizontalGroup(

panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(panNuevoLayout.createSequentialGroup()

.addGap(0, 43, Short.MAX_VALUE)

.addGroup(panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jLabel1)

.addGroup(panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

.addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGroup(panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jLabel3)

.addComponent(jLabel2)

.addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))

.addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))

.addContainerGap(49, Short.MAX_VALUE))

.addGroup(panNuevoLayout.createSequentialGroup()

.addGap(121, 121, 121)

.addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

);

panNuevoLayout.setVerticalGroup(

panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(panNuevoLayout.createSequentialGroup()

.addGap(8, 8, 8)

.addComponent(jLabel1)

.addGap(18, 18, 18)

.addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addComponent(jLabel2)

.addGap(18, 18, 18)

.addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addComponent(jLabel3)

.addGap(15, 15, 15)

.addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(50, 50, 50)

.addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(61, Short.MAX_VALUE))

);



javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

getContentPane().setLayout(layout);

layout.setHorizontalGroup(

layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(layout.createSequentialGroup()

.addGap(20, 20, 20)

.addComponent(panNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(15, Short.MAX_VALUE))

);

layout.setVerticalGroup(

layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(layout.createSequentialGroup()

.addContainerGap()

.addComponent(panNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(40, Short.MAX_VALUE))

);



pack();

}// </editor-fold>



private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {

// TODO add your handling code here:

}



private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {

insertarDatos();

}





// Variables declaration - do not modify

private javax.swing.JButton btnRegistrar;

private javax.swing.JLabel jLabel1;

private javax.swing.JLabel jLabel2;

private javax.swing.JLabel jLabel3;

private javax.swing.JPanel panNuevo;

private javax.swing.JTextField txtDir;

private javax.swing.JTextField txtEmail;

private javax.swing.JTextField txtNombre;


}



