/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.basededatos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ErickJimz
 */ 
public class MyQuery extends javax.swing.JInternalFrame {
DefaultTableModel tabla;
    /**
     * Creates new form MyQuery
     */
    public MyQuery() {
        initComponents();
    }

    void ConsultarDatos(String dato){
        String[] encabezado = {"Nombre", "Dirección", "Email"};
        String[] filas = new String[4];
        String senSQL = "";
        
        conexionMySQL cmysql = new conexionMySQL();
        Connection conec = cmysql.Conectar();
        
        senSQL = "SELECT Nombre,Direccion,Email,FROM agenda "+
        "WHERE CONCAT (Nombre,' ',Direccion, ' ', Email () LIKE  ' %" + dato+"%'";
        
        try{
            Statement st = conec.createStatement();
            ResultSet rs = st.executeQuery(senSQL);
            
            while(rs.next()){
                filas[0]=rs.getString("Nombre");
                filas[1]=rs.getString("Direccion");
                filas[2]=rs.getString("Email");
                
                tabla.addRow(filas);
            }
            this.tblRegistros.setModel(tabla);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panConsulta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();

        jLabel1.setText("Ingrese Busqueda");

        txtDato.addActionListener(this::txtDatoActionPerformed);

        btnBusqueda.setText("Search");
        btnBusqueda.addActionListener(this::btnBusquedaActionPerformed);

        btnMostrar.setText("Show All");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        tblRegistros.setForeground(new java.awt.Color(0, 204, 0));
        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistros.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tblRegistros);

        javax.swing.GroupLayout panConsultaLayout = new javax.swing.GroupLayout(panConsulta);
        panConsulta.setLayout(panConsultaLayout);
        panConsultaLayout.setHorizontalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBusqueda)
                        .addGap(35, 35, 35)
                        .addComponent(btnMostrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panConsultaLayout.setVerticalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusqueda)
                    .addComponent(btnMostrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(297, 297, 297))
        );

        pack();
    }// </editor-fold>                        

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {                                            
  String d=this.txtDato.getText();
  ConsultarDatos(d);
    }                                           

    private void txtDatoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {                                           
 String d="";
  ConsultarDatos(d);
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panConsulta;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtDato;
    // End of variables declaration                   
}
